<?php

declare(strict_types=1);

return [
    'install' => [
        ['methods' => ['GET'], 'path' => '/install', 'controller' => 'install', 'action' => 'index'],
        ['methods' => ['POST'], 'path' => '/install/check', 'controller' => 'install', 'action' => 'check'],
        ['methods' => ['POST'], 'path' => '/install/database', 'controller' => 'install', 'action' => 'database'],
        ['methods' => ['POST'], 'path' => '/install/admin', 'controller' => 'install', 'action' => 'admin'],
        ['methods' => ['POST'], 'path' => '/install/site', 'controller' => 'install', 'action' => 'site'],
        ['methods' => ['POST'], 'path' => '/install/finish', 'controller' => 'install', 'action' => 'finish'],
        ['methods' => ['GET'], 'path' => '/{path:any}', 'type' => 'redirect', 'to' => '/install'],
    ],
    'app' => [
        ['methods' => ['GET'], 'path' => '/admin/login', 'controller' => 'auth', 'action' => 'showLogin'],
        ['methods' => ['POST'], 'path' => '/admin/login', 'controller' => 'auth', 'action' => 'login'],
        ['methods' => ['POST'], 'path' => '/admin/logout', 'controller' => 'auth', 'action' => 'logout'],
        ['methods' => ['GET'], 'path' => '/admin/password-reset', 'controller' => 'auth', 'action' => 'showPasswordResetRequest'],
        ['methods' => ['POST'], 'path' => '/admin/password-reset', 'controller' => 'auth', 'action' => 'requestPasswordReset'],
        ['methods' => ['GET'], 'path' => '/admin/password-reset/{token}', 'controller' => 'auth', 'action' => 'showPasswordResetConfirm'],
        ['methods' => ['POST'], 'path' => '/admin/password-reset/{token}', 'controller' => 'auth', 'action' => 'confirmPasswordReset'],
        ['methods' => ['GET'], 'path' => '/admin', 'controller' => 'dashboard', 'action' => 'index'],
        ['methods' => ['GET'], 'path' => '/admin/pages', 'controller' => 'page', 'action' => 'index'],
        ['methods' => ['GET'], 'path' => '/admin/pages/create', 'controller' => 'page', 'action' => 'create'],
        ['methods' => ['POST'], 'path' => '/admin/pages', 'controller' => 'page', 'action' => 'store'],
        ['methods' => ['GET'], 'path' => '/admin/pages/{id}/edit', 'controller' => 'page', 'action' => 'edit'],
        ['methods' => ['POST'], 'path' => '/admin/pages/{id}', 'controller' => 'page', 'action' => 'update'],
        ['methods' => ['POST'], 'path' => '/admin/pages/{id}/delete', 'controller' => 'page', 'action' => 'delete'],
        ['methods' => ['POST'], 'path' => '/admin/pages/{id}/publish', 'controller' => 'page', 'action' => 'publish'],
        ['methods' => ['POST'], 'path' => '/admin/pages/{id}/archive', 'controller' => 'page', 'action' => 'archive'],
        ['methods' => ['GET'], 'path' => '/admin/posts', 'type' => 'redirect', 'to' => '/admin/pages'],
        ['methods' => ['GET'], 'path' => '/admin/posts/create', 'type' => 'redirect', 'to' => '/admin/pages/create'],
        ['methods' => ['GET'], 'path' => '/admin/posts/{id}/edit', 'type' => 'redirect', 'to' => '/admin/pages/{id}/edit'],
        ['methods' => ['GET'], 'path' => '/admin/forms', 'controller' => 'form', 'action' => 'index'],
        ['methods' => ['GET'], 'path' => '/admin/forms/create', 'controller' => 'form', 'action' => 'create'],
        ['methods' => ['POST'], 'path' => '/admin/forms', 'controller' => 'form', 'action' => 'store'],
        ['methods' => ['GET'], 'path' => '/admin/forms/{id}/edit', 'controller' => 'form', 'action' => 'edit'],
        ['methods' => ['POST'], 'path' => '/admin/forms/{id}', 'controller' => 'form', 'action' => 'update'],
        ['methods' => ['GET'], 'path' => '/admin/forms/{id}/submissions', 'controller' => 'form', 'action' => 'submissions'],
        ['methods' => ['GET'], 'path' => '/admin/comments', 'controller' => 'comment', 'action' => 'index'],
        ['methods' => ['POST'], 'path' => '/admin/comments/{id}/approve', 'controller' => 'comment', 'action' => 'approve'],
        ['methods' => ['POST'], 'path' => '/admin/comments/{id}/spam', 'controller' => 'comment', 'action' => 'spam'],
        ['methods' => ['POST'], 'path' => '/admin/comments/{id}/delete', 'controller' => 'comment', 'action' => 'delete'],
        ['methods' => ['GET'], 'path' => '/admin/analytics', 'controller' => 'analytics', 'action' => 'index'],
        ['methods' => ['GET'], 'path' => '/admin/backups', 'controller' => 'backup', 'action' => 'index'],
        ['methods' => ['POST'], 'path' => '/admin/backups/create', 'controller' => 'backup', 'action' => 'create'],
        ['methods' => ['GET'], 'path' => '/admin/backups/download/{name}/{file:any}', 'controller' => 'backup', 'action' => 'download'],
        ['methods' => ['GET'], 'path' => '/admin/media', 'controller' => 'media', 'action' => 'index'],
        ['methods' => ['POST'], 'path' => '/admin/media/upload', 'controller' => 'media', 'action' => 'upload'],
        ['methods' => ['POST'], 'path' => '/admin/media/{id}', 'controller' => 'media', 'action' => 'update'],
        ['methods' => ['POST'], 'path' => '/admin/media/{id}/delete', 'controller' => 'media', 'action' => 'delete'],
        ['methods' => ['GET'], 'path' => '/admin/menus', 'controller' => 'menu', 'action' => 'index'],
        ['methods' => ['POST'], 'path' => '/admin/menus', 'controller' => 'menu', 'action' => 'store'],
        ['methods' => ['GET'], 'path' => '/admin/menus/{id}/edit', 'controller' => 'menu', 'action' => 'edit'],
        ['methods' => ['POST'], 'path' => '/admin/menus/{id}', 'controller' => 'menu', 'action' => 'update'],
        ['methods' => ['GET'], 'path' => '/admin/template-modules', 'controller' => 'template_module', 'action' => 'index'],
        ['methods' => ['POST'], 'path' => '/admin/template-modules', 'controller' => 'template_module', 'action' => 'update'],
        ['methods' => ['GET'], 'path' => '/admin/settings', 'controller' => 'settings', 'action' => 'index'],
        ['methods' => ['POST'], 'path' => '/admin/settings', 'controller' => 'settings', 'action' => 'update'],
        ['methods' => ['GET'], 'path' => '/admin/{section}', 'controller' => 'module_placeholder', 'action' => 'show'],
        ['methods' => ['GET'], 'path' => '/', 'controller' => 'public_page', 'action' => 'show', 'defaults' => ['path' => '']],
        ['methods' => ['GET'], 'path' => '/sitemap.xml', 'controller' => 'seo', 'action' => 'sitemap'],
        ['methods' => ['GET'], 'path' => '/robots.txt', 'controller' => 'seo', 'action' => 'robots'],
        ['methods' => ['POST'], 'path' => '/forms/submit/{form_key}', 'controller' => 'interaction', 'action' => 'submitForm'],
        ['methods' => ['POST'], 'path' => '/comments/submit/{page_id}', 'controller' => 'interaction', 'action' => 'submitComment'],
        ['methods' => ['POST'], 'path' => '/likes/toggle/{page_id}', 'controller' => 'interaction', 'action' => 'toggleLike'],
        ['methods' => ['GET'], 'path' => '/uploads/{path:any}', 'controller' => 'upload_asset', 'action' => 'show'],
        ['methods' => ['GET'], 'path' => '/theme-assets/{theme}/{asset:any}', 'controller' => 'theme_asset', 'action' => 'show'],
        ['methods' => ['GET'], 'path' => '/dashboard-theme-assets/{theme}/{asset:any}', 'controller' => 'dashboard_theme_asset', 'action' => 'show'],
        ['methods' => ['GET'], 'path' => '/preview/{token}', 'controller' => 'public_page', 'action' => 'preview'],
        ['methods' => ['GET'], 'path' => '/health', 'type' => 'health'],
        ['methods' => ['GET'], 'path' => '/{path:any}', 'controller' => 'public_page', 'action' => 'show'],
    ],
];
